/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package principal;

import guarderia.Gato;
import guarderia.Perro;
import guarderia.Registro;
import java.time.LocalDateTime;

/**
 *
 * @author Dario
 */
public class Interfaz extends javax.swing.JFrame {
     Registro regs = new Registro();
     Perro pe;
     Gato ga;
    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPDatosAnimal = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTFNomAnimal = new javax.swing.JTextField();
        jBPerro = new javax.swing.JButton();
        jBGato = new javax.swing.JButton();
        jPDatosDueño = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTFNomDueño = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTFTele = new javax.swing.JTextField();
        jBRegs = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPDatosAnimal.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos animal"));

        jLabel3.setText("Nombre");

        jTFNomAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFNomAnimalActionPerformed(evt);
            }
        });

        jBPerro.setText("Perro");
        jBPerro.setEnabled(false);
        jBPerro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPerroActionPerformed(evt);
            }
        });

        jBGato.setText("Gato");
        jBGato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGatoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPDatosAnimalLayout = new javax.swing.GroupLayout(jPDatosAnimal);
        jPDatosAnimal.setLayout(jPDatosAnimalLayout);
        jPDatosAnimalLayout.setHorizontalGroup(
            jPDatosAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDatosAnimalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPDatosAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPDatosAnimalLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jBPerro, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBGato, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPDatosAnimalLayout.createSequentialGroup()
                        .addComponent(jTFNomAnimal, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPDatosAnimalLayout.setVerticalGroup(
            jPDatosAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDatosAnimalLayout.createSequentialGroup()
                .addGroup(jPDatosAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTFNomAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPDatosAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBPerro, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBGato, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPDatosDueño.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos dueño"));

        jLabel1.setText("Nombre");

        jTFNomDueño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFNomDueñoActionPerformed(evt);
            }
        });

        jLabel2.setText("Telefono");

        jTFTele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFTeleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPDatosDueñoLayout = new javax.swing.GroupLayout(jPDatosDueño);
        jPDatosDueño.setLayout(jPDatosDueñoLayout);
        jPDatosDueñoLayout.setHorizontalGroup(
            jPDatosDueñoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDatosDueñoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPDatosDueñoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPDatosDueñoLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTFNomDueño))
                    .addGroup(jPDatosDueñoLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(13, 13, 13)
                        .addComponent(jTFTele, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPDatosDueñoLayout.setVerticalGroup(
            jPDatosDueñoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDatosDueñoLayout.createSequentialGroup()
                .addGroup(jPDatosDueñoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTFNomDueño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPDatosDueñoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTFTele, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 10, Short.MAX_VALUE))
        );

        jBRegs.setText("Registrar");
        jBRegs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRegsActionPerformed(evt);
            }
        });

        jMenu1.setText("Ayuda");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Registro");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPDatosDueño, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPDatosAnimal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBRegs, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPDatosDueño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPDatosAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jBRegs, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFNomDueñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFNomDueñoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFNomDueñoActionPerformed

    private void jTFTeleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFTeleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFTeleActionPerformed

    private void jTFNomAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFNomAnimalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFNomAnimalActionPerformed

    private void jBRegsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRegsActionPerformed
        // TODO add your handling code here:
        if(jBPerro.isEnabled()){
            pe = new Perro(jTFNomDueño.getText(), jTFNomAnimal.getText(), jTFTele.getText());
            regs.crearRegistro(LocalDateTime.now(), pe);
        }
        else{
            ga = new Gato(jTFNomDueño.getText(), jTFNomAnimal.getText(), jTFTele.getText());
            regs.crearRegistro(LocalDateTime.now(), ga);
        }

    }//GEN-LAST:event_jBRegsActionPerformed

    private void jBGatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGatoActionPerformed
        // TODO add your handling code here:
        jBPerro.setEnabled(true);
        jBGato.setEnabled(false);
    }//GEN-LAST:event_jBGatoActionPerformed

    private void jBPerroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPerroActionPerformed
        // TODO add your handling code here:
        jBPerro.setEnabled(false);
        jBGato.setEnabled(true);
    }//GEN-LAST:event_jBPerroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBGato;
    private javax.swing.JButton jBPerro;
    private javax.swing.JButton jBRegs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPDatosAnimal;
    private javax.swing.JPanel jPDatosDueño;
    private javax.swing.JTextField jTFNomAnimal;
    private javax.swing.JTextField jTFNomDueño;
    private javax.swing.JTextField jTFTele;
    // End of variables declaration//GEN-END:variables
}
